version: "3.7"
services:
  git-server:
    build:
      dockerfile: gitserver.Dockerfile
      context: .
    restart: always
    ports:
      - "8090:80"
      - "5011:5000"
    volumes:
      - ./repos:/var/www/git